### ISSUE TITLE
Object   has no method 'repeat'

### ISSUE THREAD

**Issue by jadus** [mantrajs/mantra-cli#89] opened 2016-07-18 08:56 UTC
Hi
I'm trying to use mantra-cli but I get a "Object   has no method 'repeat'" error when using the generate command. Any idea why ?

**Comment by sungwoncho** [comment] 2016-07-20 02:55
Need steps to reproduce, CLI version, node version, OS.

For the time being, I think you can downgrade to `0.3.x` to fix the issue.

**Comment by jadus** [comment] 2016-07-25 22:43
{ npm: '3.9.5',
  ares: '1.9.0-DEV',
  http_parser: '1.0',
  modules: '11',
  node: '0.10.35',
  openssl: '1.0.1j',
  uv: '0.10.30',
  v8: '3.14.5.9',
  zlib: '1.2.8' }

Mantra :  0.4.0-rc.3

MacOS 10.9.5

Thanks !

**Comment by sungwoncho** [comment] 2016-09-10 00:49
How can I reproduce it?

**Comment by sungwoncho** [comment] 2016-10-21 04:04
Caused because node 0.10.x does not have `String.prototype.repeat`. Fixed in https://github.com/mantrajs/mantra-cli/commit/09ba433d9f7be6578c5347e8f96702f924714c46.

**Closed as completed by sungwoncho** 2016-10-21 04:04 UTC
