### ISSUE TITLE
0.3.2 Issue => $mantra create = Halt on init

### ISSUE THREAD

**Issue by Mindgames** [mantrajs/mantra-cli#27] opened 2016-03-06 00:47 UTC
After updating to 0.3.2 `mantra create` is not working as expected.  

```
$mantra c myapp
$create  myapp/
$invoke  init
```

And then it halts creating just 2 empty folders "myapp" & "test"  

Downgraded to 0.3.1 make it work as expected

**Comment by sungwoncho** [comment] 2016-03-06 01:38
This is not likely an issue with 0.3.2 as I could not reproduce. If any of [these](https://github.com/mantrajs/mantra-cli/blob/master/lib/commands/create.js#L17-L22) fails, the invoke script will halt and exit because we are doing [this](https://github.com/mantrajs/mantra-cli/blob/master/lib/commands/create.js#L16).

For instance, if meteor is not installed, [this line](https://github.com/mantrajs/mantra-cli/blob/master/lib/commands/create.js#L18) will return an error and the script will exit. We should account for unhappy scenarios like this. PR is welcomed.

Can you help me debug this issue? Just remove [this line](https://github.com/mantrajs/mantra-cli/blob/master/lib/commands/create.js#L16) and [silent option](https://github.com/mantrajs/mantra-cli/blob/master/lib/commands/create.js#L18) from your `/usr/local/lib/node_modules/mantra-cli/dist/commands/create.js` or wherever the module is installed and try to run the command. It will give you an informative error message.

**Comment by sungwoncho** [comment] 2016-03-15 07:13
Please use the latest version ([v0.3.5](https://github.com/mantrajs/mantra-cli/blob/master/RELEASE_NOTE.md#035-march-15-2016) at the moment) and use `--verbose` option for `mantra create` to debug. Closing for now as no information is available.

**Closed as completed by sungwoncho** 2016-03-15 07:13 UTC
